"""create http logs table

Revision ID: bf2a8e613acb
Revises: 
Create Date: 2026-06-29 00:19:22.596727+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2a8e613acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('raw_log', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_http_logs_created_at', 'http_logs', ['created_at'], unique=False)
    op.create_index('ix_http_logs_method', 'http_logs', ['method'], unique=False)
    op.create_index('ix_http_logs_status_code', 'http_logs', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_http_logs_status_code', table_name='http_logs')
    op.drop_index('ix_http_logs_method', table_name='http_logs')
    op.drop_index('ix_http_logs_created_at', table_name='http_logs')
    op.drop_table('http_logs')
    # ### end Alembic commands ###
